language: go
go:
        - '1.6'
        - '1.8'
script: 
        - $GOPATH/bin/curl-a-joke &
        - sleep 5
        - curl localhost:8080
jobs:
        include:
                - stage: deploy
                  script: bash .deploy.sh
