language: go
go:
        - '1.6'
        - '1.8'
jobs:
        include:
                - stage: deploy
                  script: curl -H "Content-Type: application/json" --data '{"build": true}' -X POST ${DOCKER_TRIGGER}
